// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace GuildDataApi.Models
{
    public partial class RightsTemplate
    {
        public RightsTemplate()
        {
            User = new HashSet<User>();
        }

        public int IdRightsTemplate { get; set; }
        public string Description { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsInitialUser { get; set; }

        [JsonIgnore]
        public virtual ICollection<User> User { get; set; }
    }
}